name: Java CI with Maven

on:
  push:
    branches: [ "qa" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Pwd
        run: pwd
      - name: List repo contents
        run: ls -la
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Hello world action step
        id: hello
        uses: Jacobsonius/hello-world-docker-action@DockerHub
        with:
          key: aaaa
          input_file: pom.xml
          output_file: qa.json