name: Java CI with Maven

on:
  push:
    branches: [ "qa" ]
  pull_request:
    branches: [ "master" ]

jobs:
  attempt-0: # Generating LLM index
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean # verify

      - name: Save JUnit test results
        if: always()  # even if the tests failed
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports/*.xml

      - name: Save Jacoco coverage report
        if: always()  # even if the tests failed
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html

#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ env.DOCKER_USERNAME }}
#          password: ${{ env.DOCKER_PASSWORD }}

      - name: Generating project llm index
        id: QA
        uses: Jacobsonius/hello-world-docker-action@DockerHub
        with:
          key: ${{ secrets.KEY }}
          action-name: INDEX
          input-dir: ./src/main/java/com/sampleservice/demo/config
          output-dir: .

      - name: Show files
        run: ls -la

      - name: Save Index
        uses: actions/upload-artifact@v4
        with:
          name: llm-index
          path: ".qa"

  attempt-1: # Первая попытка сгенерировать и скомпилировать тесты
    if: needs.attempt-1.result != 'failure'
    needs: attempt-0
    uses: ./.github/workflows/reusable.yml
    with:
      attempt: 1

  attempt-2: # Вторая попытка сгенерировать и скомпилировать тесты
    if: needs.attempt-1.result == 'failure'
    needs: attempt-1
    uses: ./.github/workflows/reusable.yml
    with:
      attempt: 2

  attempt-3:  # Третья попытка сгенерировать и скомпилировать тесты
    if: needs.attempt-2.result == 'failure'
    needs: attempt-2
    uses: ./.github/workflows/reusable.yml
    with:
      attempt: 3