name: Java CI with Maven

on:
  push:
    branches: [ "qa" ]
  pull_request:
    branches: [ "master" ]

jobs:
  attempt-0: # Generating LLM index
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean verify

      - name: Save test report
        if: always()  # even if the tests failed
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: target/surefire-reports/*.xml

      - name: Save coverage report
        if: always()  # even if the tests failed
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html

      - name: Generating project llm index
        id: QAIndex
        uses: Jacobsonius/hello-world-docker-action@DockerHub
        with:
          key: ${{ secrets.KEY }}
          action-name: INDEX
          target-value: '80'
          test-report-dir: ./target
          coverage-report-dir: ./target
          input-dir: ./
          output-dir: ./

      - name: Save Index
        uses: actions/upload-artifact@v4
        with:
          name: llm-index
          include-hidden-files: true
          path: .qa

  attempt-1:
    if: needs.attempt-1.result != 'failure'
    needs: attempt-0
    uses: ./.github/workflows/reusable.yml
    with:
      attempt: 1

  attempt-2:
    if: needs.attempt-1.result == 'failure'
    needs: attempt-1
    uses: ./.github/workflows/reusable.yml
    with:
      attempt: 2

  attempt-3:
    if: needs.attempt-2.result == 'failure'
    needs: attempt-2
    uses: ./.github/workflows/reusable.yml
    with:
      attempt: 3


      #      - name: Log in to Docker Hub
      #        uses: docker/login-action@v3
      #        with:
      #          username: ${{ env.DOCKER_USERNAME }}
      #          password: ${{ env.DOCKER_PASSWORD }}