name: Java CI with Maven

on:
  push:
    branches: [ "qa" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Pwd
        run: pwd

      - name: List repo contents
        run: ls -la
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ env.DOCKER_USERNAME }}
#          password: ${{ env.DOCKER_PASSWORD }}
      - name: QA action step
        id: Test
        uses: Jacobsonius/hello-world-docker-action@DockerHub
        with:
          key: ${{ secrets.KEY }}
          input_file: pom.xml
          output_file: qa.json

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto update QA"
          #            auto-merge: true
          branch: auto/update-report
          title: "Auto update QA"
          body: "This PR was automatically created from GitHub QA Assistance Actions"
          base: main