name: reusable-build

on:
  workflow_call:
    inputs:
      attempt:
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download LLM index
        uses: actions/download-artifact@v4
        with:
          name: llm-index
          path: qa.json

      - name: Show files
        run: ls -la

      - name: Show qa.json files
        ls -la qa.json/

#     Генерация тестов

      - name: Build and test (Attempt ${{ inputs.attempt }})
        run: mvn clean verify

      - name: Save JUnit test results
        if: always()  # даже если тесты упали
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          overwrite: true
          path: target/surefire-reports/*.xml

      - name: Save Jacoco coverage report
        if: always()  # даже если тесты упали
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          overwrite: true
          path: target/site/jacoco/index.html

#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v5
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          commit-message: "Auto update QA"
#          #            auto-merge: true
#          branch: auto/update-report
#          title: "Auto update QA"
#          body: "This PR was automatically created from GitHub QA Assistance Actions"
#          base: master