name: test-build

on:
  workflow_call:
    inputs:
      attempt:
        required: true
        type: number

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download LLM index
        uses: actions/download-artifact@v4
        with:
          name: junit-results
          path: .qa

      - name: Download test report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: target/surefire-reports/

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: llm-index
          path: target/site/jacoco

      - name: Show files #debug
        run: ls -la

      - name: Show .qa files
        run: ls -la .qa/ #debug

      - name: Generating test plan
        id: QATestPlan
        uses: Jacobsonius/hello-world-docker-action@DockerHub
        with:
          key: ${{ secrets.KEY }}
          action-name: PLAN
          target-value: '80'
          test-report-dir: ./target
          coverage-report-dir: ./target
          input-dir: ./
          output-dir: ./

      - name: Show files #debug
        run: ls -la

      - name: Show .plan files
        run: ls -la .plan/ #debug

      - name: Update tests
        id: QAUpdateTests
        uses: Jacobsonius/hello-world-docker-action@DockerHub
        with:
          key: ${{ secrets.KEY }}
          action-name: JUNIT_UPDATE
          target-value: '80'
          test-report-dir: ./target
          coverage-report-dir: ./target
          input-dir: ./
          output-dir: ./

      - name: Build and re-test (Attempt ${{ inputs.attempt }})
        run: mvn clean verify

      - name: Save JUnit test results
        if: always()  # даже если тесты упали
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          overwrite: true
          path: target/surefire-reports/*.xml

      - name: Save Jacoco coverage report
        if: always()  # даже если тесты упали
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          overwrite: true
          path: target/site/jacoco/index.html

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto update QA"
          #            auto-merge: true
          branch: auto/update-report
          title: "Auto update QA"
          body: "This PR was automatically created from GitHub QA Assistance Actions"
          base: master